Build script now uses default value for output file

diff --git a/build b/build
--- a/build
+++ b/build
@@ -60,9 +60,11 @@ fi
 
 # Check for output file arg length
 if [[ ! $outFile ]]; then
-	printf "Error: No output file was defined with the --output or -o parameter\n"
-	printf "       Trying running with the --help or -h flag for help\n"
-	exit 4
+	printf "Using default value 'ava' for output file\n"
+	outFile="ava"
+#	printf "Error: No output file was defined with the --output or -o parameter\n"
+#	printf "       Trying running with the --help or -h flag for help\n"
+#	exit 4
 fi
 
 # Check for root if it being integrated
